name: Deploy

on: push

jobs:
  build_native_lib:
    runs-on: ubuntu-latest
    steps:
      - name: check out lib
        uses: actions/checkout@v4
        with:
          repository: 'sqlitecloud/sdk'
      - name: build lib
        run: |
          mkdir LibreSSL
          cd LibreSSL
          wget https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-3.8.1.tar.gz
          tar xzf libressl-3.8.1.tar.gz
          cd libressl-3.8.1
          sudo ./configure --prefix=/usr/local/lib/ --with-openssldir=/usr/local/lib/ 
          sudo make install
          echo "libre ssl COMPLETED"
          ls -la /usr/local/lib/lib/
          echo "^^^^ LIB ^^^^^^"
          cd ../..
          cd C
          sudo make libsqcloud.so

  tests:
    # containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `postgres-job` executes in
    container: python:3.10
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
            python -m pip install -r requirements.txt
            python -m pip install -r requirements-dev.txt
      - name: Linting and Testing
        env: 
          TEST_CONNECTION_URL: ${{secrets.TEST_CONNECTION_URL}}
        run: |
              export PYTHONPATH=$PYTHONPATH:$(pwd)/src
              make lint

  release:
    if: ${{ github.ref == 'refs/heads/mimmo' }}
    needs: tests
    name: Release 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Set version
        run: |
              git config --local user.email "github-actions[bot]@users.noreply.github.com"
              git config --local user.name "github-actions[bot]"
              python -m pip install -r requirements-dev.txt
              bump2version patch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true